/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as PowerOnRouteImport } from './routes/power-on'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AguardandoRouteImport } from './routes/aguardando'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppPaymentRouteImport } from './routes/_app.payment'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCreateRouteImport } from './routes/_app.create'
import { Route as AppComprovantesRouteImport } from './routes/_app.comprovantes'
import { Route as AppAdmindevRouteImport } from './routes/_app.admindev'
import { Route as AppAdminSupportRouteImport } from './routes/_app.admin-support'
import { Route as AppAdminExecRouteImport } from './routes/_app.admin-exec'
import { Route as AppAdminAuditRouteImport } from './routes/_app.admin-audit'
import { Route as ApiPublicAsaasWebhookRouteImport } from './routes/api/public/asaas-webhook'
import { Route as AppCampaignIdRouteImport } from './routes/_app.campaign.$id'
import { Route as ApiPublicHooksSendPushDailyRouteImport } from './routes/api/public/hooks/send-push-daily'
import { Route as ApiPublicHooksMetaMetricsSyncRouteImport } from './routes/api/public/hooks/meta-metrics-sync'
import { Route as ApiPublicHooksAiReviewCronRouteImport } from './routes/api/public/hooks/ai-review-cron'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PowerOnRoute = PowerOnRouteImport.update({
  id: '/power-on',
  path: '/power-on',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AguardandoRoute = AguardandoRouteImport.update({
  id: '/aguardando',
  path: '/aguardando',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppPaymentRoute = AppPaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCreateRoute = AppCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AppRoute,
} as any)
const AppComprovantesRoute = AppComprovantesRouteImport.update({
  id: '/comprovantes',
  path: '/comprovantes',
  getParentRoute: () => AppRoute,
} as any)
const AppAdmindevRoute = AppAdmindevRouteImport.update({
  id: '/admindev',
  path: '/admindev',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminSupportRoute = AppAdminSupportRouteImport.update({
  id: '/admin-support',
  path: '/admin-support',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminExecRoute = AppAdminExecRouteImport.update({
  id: '/admin-exec',
  path: '/admin-exec',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminAuditRoute = AppAdminAuditRouteImport.update({
  id: '/admin-audit',
  path: '/admin-audit',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicAsaasWebhookRoute = ApiPublicAsaasWebhookRouteImport.update({
  id: '/api/public/asaas-webhook',
  path: '/api/public/asaas-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCampaignIdRoute = AppCampaignIdRouteImport.update({
  id: '/campaign/$id',
  path: '/campaign/$id',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicHooksSendPushDailyRoute =
  ApiPublicHooksSendPushDailyRouteImport.update({
    id: '/api/public/hooks/send-push-daily',
    path: '/api/public/hooks/send-push-daily',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksMetaMetricsSyncRoute =
  ApiPublicHooksMetaMetricsSyncRouteImport.update({
    id: '/api/public/hooks/meta-metrics-sync',
    path: '/api/public/hooks/meta-metrics-sync',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksAiReviewCronRoute =
  ApiPublicHooksAiReviewCronRouteImport.update({
    id: '/api/public/hooks/ai-review-cron',
    path: '/api/public/hooks/ai-review-cron',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aguardando': typeof AguardandoRoute
  '/login': typeof LoginRoute
  '/power-on': typeof PowerOnRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/admin-audit': typeof AppAdminAuditRoute
  '/admin-exec': typeof AppAdminExecRoute
  '/admin-support': typeof AppAdminSupportRoute
  '/admindev': typeof AppAdmindevRoute
  '/comprovantes': typeof AppComprovantesRoute
  '/create': typeof AppCreateRoute
  '/dashboard': typeof AppDashboardRoute
  '/payment': typeof AppPaymentRoute
  '/settings': typeof AppSettingsRoute
  '/campaign/$id': typeof AppCampaignIdRoute
  '/api/public/asaas-webhook': typeof ApiPublicAsaasWebhookRoute
  '/api/public/hooks/ai-review-cron': typeof ApiPublicHooksAiReviewCronRoute
  '/api/public/hooks/meta-metrics-sync': typeof ApiPublicHooksMetaMetricsSyncRoute
  '/api/public/hooks/send-push-daily': typeof ApiPublicHooksSendPushDailyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aguardando': typeof AguardandoRoute
  '/login': typeof LoginRoute
  '/power-on': typeof PowerOnRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/admin-audit': typeof AppAdminAuditRoute
  '/admin-exec': typeof AppAdminExecRoute
  '/admin-support': typeof AppAdminSupportRoute
  '/admindev': typeof AppAdmindevRoute
  '/comprovantes': typeof AppComprovantesRoute
  '/create': typeof AppCreateRoute
  '/dashboard': typeof AppDashboardRoute
  '/payment': typeof AppPaymentRoute
  '/settings': typeof AppSettingsRoute
  '/campaign/$id': typeof AppCampaignIdRoute
  '/api/public/asaas-webhook': typeof ApiPublicAsaasWebhookRoute
  '/api/public/hooks/ai-review-cron': typeof ApiPublicHooksAiReviewCronRoute
  '/api/public/hooks/meta-metrics-sync': typeof ApiPublicHooksMetaMetricsSyncRoute
  '/api/public/hooks/send-push-daily': typeof ApiPublicHooksSendPushDailyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/aguardando': typeof AguardandoRoute
  '/login': typeof LoginRoute
  '/power-on': typeof PowerOnRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/_app/admin-audit': typeof AppAdminAuditRoute
  '/_app/admin-exec': typeof AppAdminExecRoute
  '/_app/admin-support': typeof AppAdminSupportRoute
  '/_app/admindev': typeof AppAdmindevRoute
  '/_app/comprovantes': typeof AppComprovantesRoute
  '/_app/create': typeof AppCreateRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/payment': typeof AppPaymentRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/campaign/$id': typeof AppCampaignIdRoute
  '/api/public/asaas-webhook': typeof ApiPublicAsaasWebhookRoute
  '/api/public/hooks/ai-review-cron': typeof ApiPublicHooksAiReviewCronRoute
  '/api/public/hooks/meta-metrics-sync': typeof ApiPublicHooksMetaMetricsSyncRoute
  '/api/public/hooks/send-push-daily': typeof ApiPublicHooksSendPushDailyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aguardando'
    | '/login'
    | '/power-on'
    | '/privacidade'
    | '/termos'
    | '/admin-audit'
    | '/admin-exec'
    | '/admin-support'
    | '/admindev'
    | '/comprovantes'
    | '/create'
    | '/dashboard'
    | '/payment'
    | '/settings'
    | '/campaign/$id'
    | '/api/public/asaas-webhook'
    | '/api/public/hooks/ai-review-cron'
    | '/api/public/hooks/meta-metrics-sync'
    | '/api/public/hooks/send-push-daily'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aguardando'
    | '/login'
    | '/power-on'
    | '/privacidade'
    | '/termos'
    | '/admin-audit'
    | '/admin-exec'
    | '/admin-support'
    | '/admindev'
    | '/comprovantes'
    | '/create'
    | '/dashboard'
    | '/payment'
    | '/settings'
    | '/campaign/$id'
    | '/api/public/asaas-webhook'
    | '/api/public/hooks/ai-review-cron'
    | '/api/public/hooks/meta-metrics-sync'
    | '/api/public/hooks/send-push-daily'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/aguardando'
    | '/login'
    | '/power-on'
    | '/privacidade'
    | '/termos'
    | '/_app/admin-audit'
    | '/_app/admin-exec'
    | '/_app/admin-support'
    | '/_app/admindev'
    | '/_app/comprovantes'
    | '/_app/create'
    | '/_app/dashboard'
    | '/_app/payment'
    | '/_app/settings'
    | '/_app/campaign/$id'
    | '/api/public/asaas-webhook'
    | '/api/public/hooks/ai-review-cron'
    | '/api/public/hooks/meta-metrics-sync'
    | '/api/public/hooks/send-push-daily'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AguardandoRoute: typeof AguardandoRoute
  LoginRoute: typeof LoginRoute
  PowerOnRoute: typeof PowerOnRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  TermosRoute: typeof TermosRoute
  ApiPublicAsaasWebhookRoute: typeof ApiPublicAsaasWebhookRoute
  ApiPublicHooksAiReviewCronRoute: typeof ApiPublicHooksAiReviewCronRoute
  ApiPublicHooksMetaMetricsSyncRoute: typeof ApiPublicHooksMetaMetricsSyncRoute
  ApiPublicHooksSendPushDailyRoute: typeof ApiPublicHooksSendPushDailyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/power-on': {
      id: '/power-on'
      path: '/power-on'
      fullPath: '/power-on'
      preLoaderRoute: typeof PowerOnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aguardando': {
      id: '/aguardando'
      path: '/aguardando'
      fullPath: '/aguardando'
      preLoaderRoute: typeof AguardandoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payment': {
      id: '/_app/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof AppPaymentRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/create': {
      id: '/_app/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof AppCreateRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/comprovantes': {
      id: '/_app/comprovantes'
      path: '/comprovantes'
      fullPath: '/comprovantes'
      preLoaderRoute: typeof AppComprovantesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admindev': {
      id: '/_app/admindev'
      path: '/admindev'
      fullPath: '/admindev'
      preLoaderRoute: typeof AppAdmindevRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin-support': {
      id: '/_app/admin-support'
      path: '/admin-support'
      fullPath: '/admin-support'
      preLoaderRoute: typeof AppAdminSupportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin-exec': {
      id: '/_app/admin-exec'
      path: '/admin-exec'
      fullPath: '/admin-exec'
      preLoaderRoute: typeof AppAdminExecRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin-audit': {
      id: '/_app/admin-audit'
      path: '/admin-audit'
      fullPath: '/admin-audit'
      preLoaderRoute: typeof AppAdminAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/asaas-webhook': {
      id: '/api/public/asaas-webhook'
      path: '/api/public/asaas-webhook'
      fullPath: '/api/public/asaas-webhook'
      preLoaderRoute: typeof ApiPublicAsaasWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/campaign/$id': {
      id: '/_app/campaign/$id'
      path: '/campaign/$id'
      fullPath: '/campaign/$id'
      preLoaderRoute: typeof AppCampaignIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/hooks/send-push-daily': {
      id: '/api/public/hooks/send-push-daily'
      path: '/api/public/hooks/send-push-daily'
      fullPath: '/api/public/hooks/send-push-daily'
      preLoaderRoute: typeof ApiPublicHooksSendPushDailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/meta-metrics-sync': {
      id: '/api/public/hooks/meta-metrics-sync'
      path: '/api/public/hooks/meta-metrics-sync'
      fullPath: '/api/public/hooks/meta-metrics-sync'
      preLoaderRoute: typeof ApiPublicHooksMetaMetricsSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/ai-review-cron': {
      id: '/api/public/hooks/ai-review-cron'
      path: '/api/public/hooks/ai-review-cron'
      fullPath: '/api/public/hooks/ai-review-cron'
      preLoaderRoute: typeof ApiPublicHooksAiReviewCronRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAdminAuditRoute: typeof AppAdminAuditRoute
  AppAdminExecRoute: typeof AppAdminExecRoute
  AppAdminSupportRoute: typeof AppAdminSupportRoute
  AppAdmindevRoute: typeof AppAdmindevRoute
  AppComprovantesRoute: typeof AppComprovantesRoute
  AppCreateRoute: typeof AppCreateRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppPaymentRoute: typeof AppPaymentRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppCampaignIdRoute: typeof AppCampaignIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminAuditRoute: AppAdminAuditRoute,
  AppAdminExecRoute: AppAdminExecRoute,
  AppAdminSupportRoute: AppAdminSupportRoute,
  AppAdmindevRoute: AppAdmindevRoute,
  AppComprovantesRoute: AppComprovantesRoute,
  AppCreateRoute: AppCreateRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppPaymentRoute: AppPaymentRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppCampaignIdRoute: AppCampaignIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AguardandoRoute: AguardandoRoute,
  LoginRoute: LoginRoute,
  PowerOnRoute: PowerOnRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  TermosRoute: TermosRoute,
  ApiPublicAsaasWebhookRoute: ApiPublicAsaasWebhookRoute,
  ApiPublicHooksAiReviewCronRoute: ApiPublicHooksAiReviewCronRoute,
  ApiPublicHooksMetaMetricsSyncRoute: ApiPublicHooksMetaMetricsSyncRoute,
  ApiPublicHooksSendPushDailyRoute: ApiPublicHooksSendPushDailyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
