/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PowerOnRouteImport } from './routes/power-on'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppPaymentRouteImport } from './routes/_app.payment'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCreateRouteImport } from './routes/_app.create'
import { Route as AppCampaignIdRouteImport } from './routes/_app.campaign.$id'

const PowerOnRoute = PowerOnRouteImport.update({
  id: '/power-on',
  path: '/power-on',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppPaymentRoute = AppPaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCreateRoute = AppCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AppRoute,
} as any)
const AppCampaignIdRoute = AppCampaignIdRouteImport.update({
  id: '/campaign/$id',
  path: '/campaign/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/power-on': typeof PowerOnRoute
  '/create': typeof AppCreateRoute
  '/dashboard': typeof AppDashboardRoute
  '/payment': typeof AppPaymentRoute
  '/settings': typeof AppSettingsRoute
  '/campaign/$id': typeof AppCampaignIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/power-on': typeof PowerOnRoute
  '/create': typeof AppCreateRoute
  '/dashboard': typeof AppDashboardRoute
  '/payment': typeof AppPaymentRoute
  '/settings': typeof AppSettingsRoute
  '/campaign/$id': typeof AppCampaignIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/power-on': typeof PowerOnRoute
  '/_app/create': typeof AppCreateRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/payment': typeof AppPaymentRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/campaign/$id': typeof AppCampaignIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/power-on'
    | '/create'
    | '/dashboard'
    | '/payment'
    | '/settings'
    | '/campaign/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/power-on'
    | '/create'
    | '/dashboard'
    | '/payment'
    | '/settings'
    | '/campaign/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/power-on'
    | '/_app/create'
    | '/_app/dashboard'
    | '/_app/payment'
    | '/_app/settings'
    | '/_app/campaign/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  PowerOnRoute: typeof PowerOnRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/power-on': {
      id: '/power-on'
      path: '/power-on'
      fullPath: '/power-on'
      preLoaderRoute: typeof PowerOnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payment': {
      id: '/_app/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof AppPaymentRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/create': {
      id: '/_app/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof AppCreateRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/campaign/$id': {
      id: '/_app/campaign/$id'
      path: '/campaign/$id'
      fullPath: '/campaign/$id'
      preLoaderRoute: typeof AppCampaignIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCreateRoute: typeof AppCreateRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppPaymentRoute: typeof AppPaymentRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppCampaignIdRoute: typeof AppCampaignIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCreateRoute: AppCreateRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppPaymentRoute: AppPaymentRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppCampaignIdRoute: AppCampaignIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  PowerOnRoute: PowerOnRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
